
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int E_GRABAR = 11;
  public static final int E_EJEX = 13;
  public static final int E_EQUALS = 16;
  public static final int E_ARCHIVO = 10;
  public static final int E_DG = 5;
  public static final int E_KEYIZQ = 21;
  public static final int E_STR = 7;
  public static final int E_KEYDER = 22;
  public static final int DECI = 4;
  public static final int EOF = 0;
  public static final int E_CORIZQ = 23;
  public static final int E_VALORES = 17;
  public static final int E_GENREPEST = 6;
  public static final int E_CORDER = 24;
  public static final int E_TITLEY = 19;
  public static final int E_TITLEX = 18;
  public static final int E_TITLE = 12;
  public static final int error = 1;
  public static final int E_GRAPIE = 20;
  public static final int IDENTIFICADOR = 2;
  public static final int E_DOUBLE = 8;
  public static final int E_DOSP = 26;
  public static final int E_PYC = 25;
  public static final int E_GRALINE = 9;
  public static final int LINECOMMENT = 14;
  public static final int E_CADENA = 3;
  public static final int E_COMA = 27;
  public static final int MULTILINECOMMENT = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "E_CADENA",
  "DECI",
  "E_DG",
  "E_GENREPEST",
  "E_STR",
  "E_DOUBLE",
  "E_GRALINE",
  "E_ARCHIVO",
  "E_GRABAR",
  "E_TITLE",
  "E_EJEX",
  "LINECOMMENT",
  "MULTILINECOMMENT",
  "E_EQUALS",
  "E_VALORES",
  "E_TITLEX",
  "E_TITLEY",
  "E_GRAPIE",
  "E_KEYIZQ",
  "E_KEYDER",
  "E_CORIZQ",
  "E_CORDER",
  "E_PYC",
  "E_DOSP",
  "E_COMA"
  };
}

