
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int E_GRABAR = 13;
  public static final int E_EJEX = 15;
  public static final int E_EQUALS = 18;
  public static final int E_ARCHIVO = 12;
  public static final int E_DG = 7;
  public static final int E_KEYIZQ = 23;
  public static final int E_STR = 9;
  public static final int E_KEYDER = 24;
  public static final int DECI = 4;
  public static final int EOF = 0;
  public static final int E_CORIZQ = 25;
  public static final int E_VALORES = 19;
  public static final int E_GENREPEST = 8;
  public static final int E_CORDER = 26;
  public static final int E_TITLEY = 21;
  public static final int E_COMPARE = 5;
  public static final int E_TITLEX = 20;
  public static final int E_TITLE = 14;
  public static final int error = 1;
  public static final int E_PARENTESISIZQ = 27;
  public static final int E_GRAPIE = 22;
  public static final int IDENTIFICADOR = 2;
  public static final int E_COMILLASIMPLE = 6;
  public static final int E_DOUBLE = 10;
  public static final int E_DOSP = 30;
  public static final int E_PARENTESISDER = 28;
  public static final int E_PYC = 29;
  public static final int E_GRALINE = 11;
  public static final int LINECOMMENT = 16;
  public static final int E_CADENA = 3;
  public static final int E_COMA = 31;
  public static final int MULTILINECOMMENT = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "E_CADENA",
  "DECI",
  "E_COMPARE",
  "E_COMILLASIMPLE",
  "E_DG",
  "E_GENREPEST",
  "E_STR",
  "E_DOUBLE",
  "E_GRALINE",
  "E_ARCHIVO",
  "E_GRABAR",
  "E_TITLE",
  "E_EJEX",
  "LINECOMMENT",
  "MULTILINECOMMENT",
  "E_EQUALS",
  "E_VALORES",
  "E_TITLEX",
  "E_TITLEY",
  "E_GRAPIE",
  "E_KEYIZQ",
  "E_KEYDER",
  "E_CORIZQ",
  "E_CORDER",
  "E_PARENTESISIZQ",
  "E_PARENTESISDER",
  "E_PYC",
  "E_DOSP",
  "E_COMA"
  };
}

