const TOPERACIONES = {
    SUMA: 'OP_SUMA',
    RESTA: 'OP_RESTA',
    MULTIPLICACION: 'OP_MULTIPLICACION',
    DIVISION: 'OP_DIVISION',
    POTENCIA: 'OP_POTENCIA',
    MODULO: 'OP_MODULO',
    NEGACION: 'NEGACION',
    IGUALIGUAL: 'IGUALIGUAL',
    DIFERENCIA: 'DIFERENTEA',
    MENOR: 'MENOR',
    MENORIGUAL: 'MENORIGUAL',
    MAYOR: 'MAYOR',
    MAYORIGUAL: 'MAYORIGUAL',
    OR: 'OR',
    AND: 'AND',
    NOT: 'NOT',
    MAX: 2000
}

module.exports = TOPERACIONES;