
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorJS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int E_CORDER = 28;
  public static final int E_VAR = 9;
  public static final int E_FALSE = 50;
  public static final int E_PYC = 21;
  public static final int E_TRUE = 49;
  public static final int E_MAS = 31;
  public static final int E_MAYORQUE = 45;
  public static final int E_COMA = 24;
  public static final int E_COMPARAR = 40;
  public static final int E_MODULO = 36;
  public static final int E_POR = 33;
  public static final int E_CADENA = 3;
  public static final int E_NOEQUALS = 41;
  public static final int E_CONST = 11;
  public static final int E_SWITCH = 17;
  public static final int DECI = 5;
  public static final int IDENTIFICADOR = 2;
  public static final int E_ELSE = 13;
  public static final int E_DO = 15;
  public static final int E_OOR = 47;
  public static final int E_KEYIZQ = 25;
  public static final int E_FOR = 16;
  public static final int E_PARENTESISDER = 30;
  public static final int E_AND = 46;
  public static final int E_REQUIRE = 8;
  public static final int E_MENORQUE = 44;
  public static final int E_CADENAUC = 4;
  public static final int E_POTENCIA = 35;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int E_DIVIDIR = 34;
  public static final int E_CLASS = 6;
  public static final int E_CORIZQ = 27;
  public static final int E_DEFAULT = 20;
  public static final int E_KEYDER = 26;
  public static final int E_MENOS = 32;
  public static final int E_CASE = 18;
  public static final int E_MENOR = 42;
  public static final int E_IF = 12;
  public static final int E_EQUALS = 37;
  public static final int E_BREAK = 19;
  public static final int E_CONSOLE = 7;
  public static final int E_MAYOR = 43;
  public static final int E_AUMENTO = 38;
  public static final int E_NEGAR = 48;
  public static final int E_DOSPUNTOS = 23;
  public static final int E_LET = 10;
  public static final int E_PUNTO = 22;
  public static final int E_WHILE = 14;
  public static final int E_PARENTESISIZQ = 29;
  public static final int E_DISMINUIR = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFICADOR",
  "E_CADENA",
  "E_CADENAUC",
  "DECI",
  "E_CLASS",
  "E_CONSOLE",
  "E_REQUIRE",
  "E_VAR",
  "E_LET",
  "E_CONST",
  "E_IF",
  "E_ELSE",
  "E_WHILE",
  "E_DO",
  "E_FOR",
  "E_SWITCH",
  "E_CASE",
  "E_BREAK",
  "E_DEFAULT",
  "E_PYC",
  "E_PUNTO",
  "E_DOSPUNTOS",
  "E_COMA",
  "E_KEYIZQ",
  "E_KEYDER",
  "E_CORIZQ",
  "E_CORDER",
  "E_PARENTESISIZQ",
  "E_PARENTESISDER",
  "E_MAS",
  "E_MENOS",
  "E_POR",
  "E_DIVIDIR",
  "E_POTENCIA",
  "E_MODULO",
  "E_EQUALS",
  "E_AUMENTO",
  "E_DISMINUIR",
  "E_COMPARAR",
  "E_NOEQUALS",
  "E_MENOR",
  "E_MAYOR",
  "E_MENORQUE",
  "E_MAYORQUE",
  "E_AND",
  "E_OOR",
  "E_NEGAR",
  "E_TRUE",
  "E_FALSE"
  };
}

