const TIPO_DATO = {
    ENTERO: 'ENTERO',
    DOBLE: 'DOBLE',
    BOOLEANO: 'BOOLEANO',
    CARACTER: 'CARACTER',
    CADENA: 'CADENA',
    VECTOR: 'VECTOR',
    LISTA: 'LISTA'
}

module.exports = TIPO_DATO