const TIPO_OPERACION = {
    SUMA: 'SUMA',
    RESTA: 'RESTA',
    MULTIPLICACION: 'MULTIPLICACION',
    DIVISION: 'DIVISION',
    POTENCIA: 'POTENCIA',
    MODULO: 'MODULO',
    NEGACION: 'NEGACION',
    IGUALIGUAL: 'IGUALIGUAL',
    DIFERENTE: 'DIFERENTE',
    MENOR: 'MENOR',
    MENORIGUAL: 'MENORIGUAL',
    MAYOR: 'MAYOR',
    MAYORIGUAL: 'MAYORIGUAL',
    OR: 'OR',
    AND: 'AND',
    NOT: 'NOT',
    MAX: 2000
}
module.exports = TIPO_OPERACION;