const TIPO_VALOR = {
    ENTERO: 'VAL_ENTERO',
    DOBLE: 'VAL_DOBLE',
    CADENA: 'VAL_CADENA',
    CARACTER: 'VAL_CARACTER',
    BOOLEANO: 'VAL_BOOLEANO',
    IDENTIFICADOR: 'VAL_IDENTIFICADOR'
}

module.exports = TIPO_VALOR